project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
    default: anvil
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings:
            port: 8555
            gas_limit: 8000000
            accounts: 10
            evm_version: shanghai
            mnemonic: brownie
            block_time: 0
            default_balance: 100
    live:
        gas_limit: 10000000
        gas_buffer: 1.1
        gas_price: auto
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: false

compiler:
    evm_version: shanghai
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
        #viaIR: true
        remappings: 
            - "@erc721a=./node_modules/erc721a/contracts"
            - "@chainlink=./node_modules/@chainlink/contracts/src/v0.8"
            - "@openzeppelin=./node_modules/@openzeppelin"

console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true

reports:
    exclude_paths:
        - contracts/testhelpers/**/*.*
        - contracts/openzeppelin/**/*.*
    exclude_contracts:
        - Address
        - Context
        - Ownable
        - ReentrancyGuard
        - SafeERC20
        - SafeMath
        - EnumerableBytes32Set

hypothesis:
    deadline: null
    max_examples: 50
    report_multiple_bugs: False
    stateful_step_count: 10

autofetch_sources: false
dependencies: false
dev_deployment_artifacts: false
